name: ZK-JWT tests
on: [push]
jobs:
  run_circuit_tests:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes \
            build-essential \
            libgmp-dev \
            libsodium-dev \
            nasm \
            nlohmann-json3-dev

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Enable Corepack
        run: corepack enable

      - name: Set Yarn Version
        run: corepack prepare yarn@3.2.3 --activate

      - name: Install Yarn dependencies
        working-directory: ./packages/circuits
        run: yarn install --immutable

      - name: Run Tests
        working-directory: ./packages/circuits
        run: yarn test

  run_helpers_tests:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Enable Corepack
        run: corepack enable

      - name: Set Yarn Version
        run: corepack prepare yarn@3.2.3 --activate
      
      - name: Install Yarn dependencies
        working-directory: ./packages/helpers
        run: yarn install --immutable
      
      - name: Run build
        working-directory: ./packages/helpers
        run: yarn build
     
      - name: Run Tests
        working-directory: ./packages/helpers
        run: yarn test